config/routes.rb
Rails.application.routes.draw do
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  root 'simple_pages#index'# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheKingdomOfGodTshirts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", simple_pages_about_path %></li>
        <li><%= link_to "Contact", simple_pages_contact_path %></li>
      </ul>
    </nav>

    <%= yield %>

    <footer>
      &copy; 2019 ~ Christine Lund
    </footer>
  </body>
</html>

app/views/simple_pages/about.html.erb
<h1>Making Tshirts to represent Jesus Christ. Please share.</h1>
<h2>If you have any inquiries, please feel free to contact me. These are new tshirts!</h2>
<p>This app was created with Ruby on Rails: <li><%= link_to "Home", root_path %></li></p>

app/views/simple_pages/contact.html.erb
<h1>Contact Me!</h1>
<h2>Please feel free to contact me for further inquiries</h2>
<p>You can reach me at cdlart@yahoo.com</p>

app/views/simple_pages/index.html.erb
<h1>Welcome to Victory Warrior Intercessor T-Shirts</h1>
<<h2>Sharing Jesus and Gearing Up For the Kingdom of God</h2>
<p>Welcome!! It is October 20, 2019 at 11:18pm <%= Time.now %></p>